package utils;

public enum GameState {
    MENU_SCREEN, START_LEVEL_SCREEN, RUNNING, LEVEL_COMPLETE_SCREEN, GAME_OVER_SCREEN, LEVEL_SELECTION_SCREEN, CONTROLS_MENU_SCREEN,
    LOADING, MENU_LOADING_SCREEN, START_LEVEL_LOADING_SCREEN, LEVEL_COMPLETE_LOADING_SCREEN, GAME_OVER_LOADING_SCREEN, LEVEL_SELECTION_LOADING_SCREEN, CONTROLS_MENU_LOADING_SCREEN
}
